version: "3"

services:
  visualization-streamlit:
    container_name: visualization-container
    build: ./
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - TESTNET_API=${TESTNET_API}
      - TESTNET_SECRET=${TESTNET_SECRET}
      - BINANCE_WATCH_API=${BINANCE_WATCH_API}
      - BINANCE_WATCH_SECRET=${BINANCE_WATCH_SECRET}
#    deploy:
#      resources:
#        limits:
#                #cpus: 0.25
#          memory: 256M
    volumes:
      - "../:/root/crypto-prediction"
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        cd /root/crypto-prediction
        pip install -r visualization/requirements.txt
        pip install TA-Lib
        export PYTHONPATH=$PYTHONPATH:/root/crypto-prediction
        streamlit run visualization/app.py
